/* IoT Door Opening Detector – ESP32 + FC-51 + Buzzer + LEDs + Arduino IoT Cloud
   - Detects motion/door events with IR sensor (FC-51)
   - Sounds buzzer and toggles status LED on event
   - Syncs a cloud "led" property to control an onboard LED remotely
   - Requires Arduino IoT Cloud to generate thingProperties.h
*/

#include "thingProperties.h"   // Generated by Arduino IoT Cloud (add to project via Cloud setup)
#include <Arduino.h>

// ---- Pin definitions (adjust to your wiring) ----
const int IRPin      = 27;   // FC-51 OUT pin
const int buzzerPin  = 26;   // Buzzer (ACTIVE buzzer recommended)
const int ledGreen   = 25;   // Green LED
const int ledBlue    = 33;   // Blue LED (cloud-controlled in onLedChange())

// Cloud variable declared in thingProperties.h (bool led;)
// Callback prototype in thingProperties.h: void onLedChange();

void setup() {
  Serial.begin(9600);
  delay(500);

  pinMode(IRPin,     INPUT);
  pinMode(buzzerPin, OUTPUT);
  pinMode(ledGreen,  OUTPUT);
  pinMode(ledBlue,   OUTPUT);

  // Initialize outputs
  digitalWrite(buzzerPin, LOW);
  digitalWrite(ledGreen,  LOW);
  digitalWrite(ledBlue,   LOW);

  // ----- Arduino IoT Cloud -----
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  // Keep the IoT Cloud connection alive and process property updates
  ArduinoCloud.update();

  // Read IR motion sensor
  int motionDetected = digitalRead(IRPin);

  if (motionDetected == LOW) { // depending on FC-51 module, LOW may indicate detection
    // Alert: buzzer ON briefly + green LED ON
    digitalWrite(buzzerPin, HIGH);
    digitalWrite(ledGreen, HIGH);
    Serial.println("Door unlock / Motion detected: OK");

    delay(1000);  // 1 second alert
    digitalWrite(buzzerPin, LOW);
    digitalWrite(ledGreen, LOW);
  }

  delay(50);
}

// ----- Cloud callback -----
// When the "led" property changes in the Arduino IoT Cloud dashboard, toggle blue LED
void onLedChange() {
  digitalWrite(ledBlue, led ? HIGH : LOW);
}
